# TODO
# - 1 deployment, que tenga 1 pod, namespace distinto
# - en el pod, viene 1 icecast
# - aplicacion ruby que envia plantilla kubernetes usando API
apiVersion: v1
kind: Namespace
metadata:
    name: testing1253
    labels:
      name: Jojo123
